# Generated by Django 3.1.3 on 2021-01-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='dars_rasmlari')),
                ('ism', models.CharField(max_length=30)),
                ('fan', models.CharField(max_length=30)),
                ('dic', models.TextField(max_length=80)),
            ],
        ),
    ]
