# Generated by Django 3.1.3 on 2021-01-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maktab', '0002_tadbirlar'),
    ]

    operations = [
        migrations.CreateModel(
            name='oqituvchilar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasmi', models.ImageField(upload_to='o`qituvchilar_rasmi')),
                ('ism_familyasi', models.CharField(max_length=35)),
                ('lavozimi', models.CharField(max_length=35)),
                ('malomut', models.CharField(max_length=35)),
            ],
        ),
    ]
