# Generated by Django 3.1.3 on 2021-01-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maktab', '0003_oqituvchilar'),
    ]

    operations = [
        migrations.CreateModel(
            name='photolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='rasmlari')),
            ],
        ),
    ]
